language: jvm

jdk: oraclejdk8

services:
  - mysql
  - rabbitmq

before_install:
  - mysql -u root  < ci.sql
  - chmod +x gradlew

script:
  - ./gradlew build -Dspring.profiles.active=ci
  - ./gradlew codeCoverageReport

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    - https://outlook.office.com/webhook/35c21aff-9cde-45a2-833a-d0aef9e7ca4a@dea6e02c-702b-45bc-9c84-c62f18599043/TravisCI/c1ff5b3361bc42a6a962f7af8ce99a78/1cdb000a-6c7b-49f2-885f-de5cf9e238cf